use test;
ALTER TABLE MattsInfo DROP FOREIGN KEY fk_mattsinfo_person_id;
ALTER TABLE MattsInfo ADD CONSTRAINT fk_mattsinfo_person_id FOREIGN KEY (person_id) REFERENCES Persons (person_id) ON DELETE CASCADE;
ALTER TABLE MattBusySlots DROP FOREIGN KEY fk_mattsinfo_mattbusyslots;
ALTER TABLE MattBusySlots ADD CONSTRAINT fk_mattsinfo_mattbusyslots FOREIGN KEY (matt_id) REFERENCES MattsInfo (matt_id) ON DELETE CASCADE;
ALTER TABLE prsin_socialNetworks DROP FOREIGN KEY fk_persons;
ALTER TABLE prsin_socialNetworks ADD CONSTRAINT fk_persons  FOREIGN KEY (person_id) REFERENCES Persons (person_id)  ON DELETE CASCADE;
ALTER TABLE prsin_socialNetworks DROP FOREIGN KEY fk_spr_networks;
ALTER TABLE prsin_socialNetworks ADD CONSTRAINT fk_spr_networks  FOREIGN KEY (sn_id) REFERENCES sprSocialNetworks (sn_id)  ON DELETE CASCADE;
ALTER TABLE Notifications DROP FOREIGN KEY fk_mattsinfo_notifications;
ALTER TABLE Notifications ADD CONSTRAINT fk_mattsinfo_notifications  FOREIGN KEY (matt_id) REFERENCES MattsInfo (matt_id)  ON DELETE CASCADE;
